# Generated by Django 5.0 on 2023-12-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_vehicles_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='company',
        ),
    ]
