# Generated by Django 5.0 on 2023-12-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_alter_vehicle_charging_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
