# Generated by Django 5.0 on 2023-12-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
